version: '3.3'
volumes:
  pg_data_volume:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data_volume:/var/lib/postgresql/data

  backend:
    image: youzoff/foodgram_backend
    env_file: ../.env
    volumes:
      - static_volume:/backend_static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: youzoff/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  nginx:
    image: youzoff/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - ../backend/templates/docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/static/
      - media_volume:/media/
